/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_enroutesystems_yugioh_NativeTableroJuego */

#ifndef _Included_com_enroutesystems_yugioh_NativeTableroJuego
#define _Included_com_enroutesystems_yugioh_NativeTableroJuego
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_enroutesystems_yugioh_NativeTableroJuego
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_enroutesystems_yugioh_NativeTableroJuego_booleanMethod
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
